config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/federation-adapter:
      branch: master
      repo: https://github.com/madgeek-arc/federation-adapter
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/federation-adapter git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cerise-cat.sh
        container: qc.acc_hilly-cerise-wasp
  QC.Doc:
    repos:
      github.com/madgeek-arc/federation-adapter find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-orange-panda.sh
        container: qc.doc_sickly-flax-budgerigar
      github.com/madgeek-arc/federation-adapter git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-mustard-malamute.sh
        container: qc.doc_wimpy-ochre-ladybird
      github.com/madgeek-arc/federation-adapter markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-amber-fowl.sh
        container: qc.doc_wimpy-olive-zonkey
  QC.Lic:
    repos:
      github.com/madgeek-arc/federation-adapter licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-aqua-zebu.sh
        container: qc.lic_smelly-vermilion-sheep
  QC.Sty:
    repos:
      github.com/madgeek-arc/federation-adapter checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-olivine-millipede.sh
        container: qc.sty_chummy-wheat-salamander
      github.com/madgeek-arc/federation-adapter jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cream-mongrel.sh
        container: qc.sty_stinky-chestnut-kiwi
  QC.Ver:
    repos:
      github.com/madgeek-arc/federation-adapter get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-indigo-buffalo.sh
        container: qc.ver_flabby-myrtle-tarantula
timeout: 5400
